[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "phony"
version = "0.0.1"
description = "Phone (VoiP) to keyboard adapter"
dependencies = [
    "click",
    "evdev",
]

[project.scripts]
pony = "cli:phony"
